"""Module I: Strategic Plan 2025-2030 — CEL org-wide outcome definitions
and cross-programme aggregation.

STRATEGIC_OUTCOMES is the fixed set of six 2030 targets from CEL's
Strategic Plan. Programme indicators are wired into an outcome via
strategic_outcome_links (see database/schema.sql); outcomes with no
automatic source fall back to strategic_outcome_manual entries.
"""
from __future__ import annotations

from database.db import run_query

STRATEGIC_OUTCOMES = [
    {
        "code": "SMES",
        "label": "Youth & women-led agribusinesses and SMEs supported",
        "target": 40_000,
        "unit": "enterprises",
    },
    {
        "code": "FINANCE",
        "label": "Blended finance & donor funding mobilised",
        "target": 40_000_000,
        "unit": "USD",
    },
    {
        "code": "PILOTS",
        "label": "Research-backed enterprises piloted or scaled",
        "target": 2_500,
        "unit": "enterprises",
    },
    {
        "code": "JOBS",
        "label": "Decent jobs created",
        "target": 80_000,
        "unit": "jobs",
    },
    {
        "code": "REVENUE",
        "label": "Cumulative revenue generated by CEL-supported enterprises",
        "target": 100_000_000,
        "unit": "USD",
    },
    {
        "code": "BDS",
        "label": "Active BDS professionals & ESO partnerships (16 regions)",
        "target": 100,
        "unit": "professionals",
    },
]

OUTCOME_BY_CODE = {o["code"]: o for o in STRATEGIC_OUTCOMES}


def _num(val, default=0.0) -> float:
    """Safely convert a DB value (string, int, float, None) to float."""
    if val is None or val == "" or val == "—":
        return default
    try:
        return float(str(val).replace(",", "").replace("%", "").replace("≥", "").replace("+", "").strip())
    except (ValueError, TypeError):
        return default


def get_outcome_progress() -> dict[str, dict]:
    """Return {outcome_code: {target, unit, auto_total, manual_total,
    combined_total, pct, breakdown: [...]}} for every strategic outcome.

    breakdown entries: {"source": "auto"|"manual", "project": str,
    "label": str, "value": float, "note": str|None}
    """
    progress = {
        o["code"]: {
            "target": o["target"],
            "unit": o["unit"],
            "label": o["label"],
            "auto_total": 0.0,
            "manual_total": 0.0,
            "breakdown": [],
        }
        for o in STRATEGIC_OUTCOMES
    }

    indicator_links = run_query(
        """
        SELECT sol.outcome_code, sol.note, p.name AS project_name,
               lr.indicator_code, lr.indicator_statement,
               rda.actual_year AS raw_value
        FROM strategic_outcome_links sol
        JOIN projects p ON p.project_id = sol.project_id
        LEFT JOIN logframe_rows lr ON lr.id = sol.logframe_row_id
        LEFT JOIN raw_data_analysis rda
               ON rda.logframe_row_id = sol.logframe_row_id
              AND rda.project_id = sol.project_id
        WHERE sol.source = 'indicator_actual_year'
        """
    )
    for row in indicator_links:
        code = row["outcome_code"]
        if code not in progress:
            continue
        value = _num(row["raw_value"])
        progress[code]["auto_total"] += value
        label = row["indicator_code"] or row["indicator_statement"] or "Indicator"
        progress[code]["breakdown"].append({
            "source": "auto", "project": row["project_name"],
            "label": label, "value": value, "note": row["note"],
        })

    budget_links = run_query(
        """
        SELECT sol.outcome_code, sol.note, p.name AS project_name, p.budget_total AS raw_value
        FROM strategic_outcome_links sol
        JOIN projects p ON p.project_id = sol.project_id
        WHERE sol.source = 'project_budget_total'
        """
    )
    for row in budget_links:
        code = row["outcome_code"]
        if code not in progress:
            continue
        value = _num(row["raw_value"])
        progress[code]["auto_total"] += value
        progress[code]["breakdown"].append({
            "source": "auto", "project": row["project_name"],
            "label": "Programme budget (funds mobilised)", "value": value, "note": row["note"],
        })

    manual_entries = run_query(
        """
        SELECT som.outcome_code, som.value, som.note, som.updated_by, som.updated_at,
               p.name AS project_name
        FROM strategic_outcome_manual som
        LEFT JOIN projects p ON p.project_id = som.project_id
        """
    )
    for row in manual_entries:
        code = row["outcome_code"]
        if code not in progress:
            continue
        value = _num(row["value"])
        progress[code]["manual_total"] += value
        progress[code]["breakdown"].append({
            "source": "manual",
            "project": row["project_name"] or "Org-wide",
            "label": f"Manually entered by {row['updated_by'] or 'Admin'}",
            "value": value, "note": row["note"],
        })

    for code, p in progress.items():
        p["combined_total"] = p["auto_total"] + p["manual_total"]
        p["pct"] = round(p["combined_total"] / p["target"] * 100, 1) if p["target"] else 0.0

    return progress
