[theme]
primaryColor             = "#F5A820"
backgroundColor          = "#FFFFFF"
secondaryBackgroundColor = "#F5F4F1"
textColor                = "#4A5568"
font                     = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
